import React from 'react';

const Spinner = () => (
  <>
    <div className="loadingio-spinner-dual-ring-inumal79cof"><div className="ldio-rx0n9iptea">
    <div></div><div><div></div></div>
    </div></div>
    <style type="text/css">
    @keyframes ldio-rx0n9iptea {
      0% { transform: rotate(0) }
      100% { transform: rotate(360deg) }
    }
    .ldio-rx0n9iptea div { box-sizing: border-box!important }
    .ldio-rx0n9iptea > div {
      position: absolute;
      width: 104px;
      height: 104px;
      top: 48px;
      left: 48px;
      border-radius: 50%;
      border: 12px solid #000;
      border-color: #292929 transparent #292929 transparent;
      animation: ldio-rx0n9iptea 1s linear infinite;
    }
    .ldio-rx0n9iptea > div:nth-child(2) { border-color: transparent }
    .ldio-rx0n9iptea > div:nth-child(2) div {
      position: absolute;
      width: 100%;
      height: 100%;
      transform: rotate(45deg);
    }
    .ldio-rx0n9iptea > div:nth-child(2) div:before, .ldio-rx0n9iptea > div:nth-child(2) div:after {
      content: "";
      display: block;
      position: absolute;
      width: 12px;
      height: 12px;
      top: -12px;
      left: 34px;
      background: #292929;
      border-radius: 50%;
      box-shadow: 0 92px 0 0 #292929;
    }
    .ldio-rx0n9iptea > div:nth-child(2) div:after {
      left: -12px;
      top: 34px;
      box-shadow: 92px 0 0 0 #292929;
    }
    .loadingio-spinner-dual-ring-inumal79cof {
      width: 200px;
      height: 200px;
      display: inline-block;
      overflow: hidden;
      background: #eafeff;
    }
    .ldio-rx0n9iptea {
      width: 100%;
      height: 100%;
      position: relative;
      transform: translateZ(0) scale(1);
      backface-visibility: hidden;
      transform-origin: 0 0; /* see note above */
    }
    .ldio-rx0n9iptea div { box-sizing: content-box; }
    /* generated by https://loading.io/ */
    </style>
  </>
);

export default Spinner;
